"""Initial schema with recipes table

Revision ID: ae42743c99d7
Revises: 
Create Date: 2025-12-27 16:24:53.435676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae42743c99d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Integer primary key for database efficiency'),
    sa.Column('uuid', sa.UUID(), nullable=False, comment='Globally unique business identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True, comment="Type of source: 'custom', 'youtube', 'photo', 'webpage', etc."),
    sa.Column('source_key', sa.String(length=500), nullable=True, comment='Unique identifier within source type (URL, video ID, hash, etc.)'),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional metadata about the source (optional)'),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recipe_cuisine', 'recipes', [sa.literal_column("(CAST(data ->> 'cuisine' AS VARCHAR))")], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_recipe_data_gin', 'recipes', ['data'], unique=False, postgresql_using='gin', postgresql_ops={'data': 'jsonb_path_ops'})
    op.create_index('idx_recipe_name', 'recipes', [sa.literal_column("(CAST(data ->> 'name' AS VARCHAR))")], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_recipe_source_unique', 'recipes', ['source_type', 'source_key'], unique=True, postgresql_where=sa.text('source_type IS NOT NULL AND source_key IS NOT NULL AND deleted_at IS NULL'))
    op.create_index(op.f('ix_recipes_source_type'), 'recipes', ['source_type'], unique=False)
    op.create_index(op.f('ix_recipes_uuid'), 'recipes', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_uuid'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_source_type'), table_name='recipes')
    op.drop_index('idx_recipe_source_unique', table_name='recipes', postgresql_where=sa.text('source_type IS NOT NULL AND source_key IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('idx_recipe_name', table_name='recipes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_recipe_data_gin', table_name='recipes', postgresql_using='gin', postgresql_ops={'data': 'jsonb_path_ops'})
    op.drop_index('idx_recipe_cuisine', table_name='recipes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('recipes')
    # ### end Alembic commands ###
