"""initial schema with enums

Revision ID: f26d330defe9
Revises: 
Create Date: 2025-12-28 16:38:07.484590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f26d330defe9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Integer primary key for database efficiency'),
    sa.Column('uuid', sa.UUID(), nullable=False, comment='Globally unique business identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Complete recipe data (title, ingredients, steps, files, etc.)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recipe_cuisine', 'recipes', [sa.literal_column("(CAST(data ->> 'cuisine' AS VARCHAR))")], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_recipe_data_gin', 'recipes', ['data'], unique=False, postgresql_using='gin', postgresql_ops={'data': 'jsonb_path_ops'})
    op.create_index('idx_recipe_name', 'recipes', [sa.literal_column("(CAST(data ->> 'name' AS VARCHAR))")], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_recipes_uuid'), 'recipes', ['uuid'], unique=True)
    op.create_table('ingestion_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False, comment='Unique identifier for this ingestion request'),
    sa.Column('recipe_id', sa.Integer(), nullable=True, comment='Recipe created from this ingestion (NULL if pending/failed)'),
    sa.Column('source_type', sa.Enum('youtube', 'webpage', 'photo', 'custom', name='sourcetype', native_enum=False), nullable=False, comment='Source type: youtube, webpage, photo, custom'),
    sa.Column('source_key', sa.String(length=500), nullable=False, comment='Unique identifier: video_id, normalized URL, image hash, etc.'),
    sa.Column('source_url', sa.String(length=1000), nullable=True, comment='Original URL submitted by user'),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'cancelled', name='ingestionstatus', native_enum=False), nullable=False, comment='Status: pending, processing, completed, failed, cancelled'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Higher = process first (0 = normal)'),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=True, comment='ID of worker processing this request'),
    sa.Column('requested_by', sa.String(length=100), nullable=True, comment='User who requested this ingestion'),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Original request parameters'),
    sa.Column('processing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Downloads, AI outputs, logs, errors - everything technical'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key')
    )
    op.create_index('idx_ingestion_queue', 'ingestion_requests', ['status', sa.literal_column('priority DESC'), 'requested_at'], unique=False, postgresql_where=sa.text("status IN ('pending', 'processing')"))
    op.create_index(op.f('ix_ingestion_requests_recipe_id'), 'ingestion_requests', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_ingestion_requests_source_type'), 'ingestion_requests', ['source_type'], unique=False)
    op.create_index(op.f('ix_ingestion_requests_status'), 'ingestion_requests', ['status'], unique=False)
    op.create_index(op.f('ix_ingestion_requests_uuid'), 'ingestion_requests', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_requests_uuid'), table_name='ingestion_requests')
    op.drop_index(op.f('ix_ingestion_requests_status'), table_name='ingestion_requests')
    op.drop_index(op.f('ix_ingestion_requests_source_type'), table_name='ingestion_requests')
    op.drop_index(op.f('ix_ingestion_requests_recipe_id'), table_name='ingestion_requests')
    op.drop_index('idx_ingestion_queue', table_name='ingestion_requests', postgresql_where=sa.text("status IN ('pending', 'processing')"))
    op.drop_table('ingestion_requests')
    op.drop_index(op.f('ix_recipes_uuid'), table_name='recipes')
    op.drop_index('idx_recipe_name', table_name='recipes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_recipe_data_gin', table_name='recipes', postgresql_using='gin', postgresql_ops={'data': 'jsonb_path_ops'})
    op.drop_index('idx_recipe_cuisine', table_name='recipes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('recipes')
    # ### end Alembic commands ###
